### ISSUE TITLE
I want to pay you to add some links 

### ISSUE THREAD

**Issue by sanayar2008** [kpulkit29/Momentum-Plugin#1]
momentum plugin clone.
1) I need to add currency today rate on the right corner of the tab .
2) I need to add momentum pro (plan) 

so what does it cost & time ?

**Comment by kpulkit29** [comment]
The API used here does not work as expected any more

**Comment by sanayar2008** [comment]
that's because momentumdash.com itself ? 
or what is the problem behind that?
does there any ability to create it for me from scratch ?

**Comment by kpulkit29** [comment]
What exactly do you want to ask

**Comment by sanayar2008** [comment]
I want to a clone of chrome or firefox (momentum) plugin one.?
could you able to create this one for me ? if yeas, what does it cost & time ?

**Comment by kpulkit29** [comment]
Currently busy with some other things sorry
